# Generated by Django 4.0.4 on 2022-05-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='addres',
            name='zip',
            field=models.CharField(default='23401', max_length=255),
        ),
    ]
